extends Node

@warning_ignore("unused_signal")
signal l_click(x: int, y: int)
@warning_ignore("unused_signal")
signal r_click(x: int, y: int)
@warning_ignore("unused_signal")
signal lvl_lose()
@warning_ignore("unused_signal")
signal lvl_win()
@warning_ignore("unused_signal")
signal redraw_lvl()
@warning_ignore("unused_signal")
signal zoom_change()
@warning_ignore("unused_signal")
signal toggle_fullscreen()
@warning_ignore("unused_signal")
signal settings_change()
@warning_ignore("unused_signal")
signal collection_change()
@warning_ignore("unused_signal")
signal regenerate_lvl()
@warning_ignore("unused_signal")
signal generate_win_loot(count: int)
@warning_ignore("unused_signal")
signal generate_shop(count: int)
